---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    auhtor: intelliqit
spec:
  containers:
    - name: webserver
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080