---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    author: intelliqit
spec:
  ports:
    - targetPort: 6372
      port: 6372
  selector:
    author: intelliqit
    name: redis