---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    author: intelliqit
    name: redis
spec:
  containers:
    - name: myredis
      image: redis
      ports:
        - containerPort: 6372
...